#!/usr/bin/env python3

#This line above tells the operating system to use python3.
#This allows the user to not have to type "python3" before the filename when running the program. 
#Type "chmod +x Fibonacci-gen" into the terminal first to make sure the file is executable.
#Then, type "./Fibonacci-gen -c 6" instead of "python3 Fibonacci-gen -c 6". 

#sys is a module that gives the code access to command-line arguments.
import sys

#This function will return the full list of Fibonacci numbers based on how many numbers it needs to generate (n).
def fibonacci(n):
	seq = []
	a, b = 0, 1
	for _ in range(n):
		seq.append(a)
		a, b = b, a + b
	return seq

#This function will print the help message for the Fibonacci generator, explaining the various command-line options available to the user.
def print_help():
	print("""
    Help for Fibonacci generator:
	   
    --help : Print this help
	
    --count|-c : Calculate to this many places. IE: 0, 1, 1, 2, 3, 5 would be the result of -c 6
    
    --one-line: Print all the numbers on one line, separated by commas. Without this option,
    each number in the sequence will be printed on a new line.
    
    --numbering: Preface each number in the sequence with it's placement: IE for “-c 6 
    --numbering --one-line” you would get this: “1:0, 2:1, 3:1, 4:2, 5:3, 6:5” where the first
    number is the count and the second is the Fibonacci sequence. Note: this argument should
    work with all other arguments.

    --last-only: Only print the last number in the sequence
    """)

#sys.argv is a list (array-like) of arguments from the command line.
#It will store all the arguments from the command line. It will skip the first argument because it's just the filename.
#For example, "./Fibonacci-gen -c 6 -one-line" is entered and this function will make args = ['-c', '6', '-one-line']
args = sys.argv[1:]

#This function will be called when the program is run. 
#It will check the arguments and call the correct functions based on what the user entered.
def main():
    print(10/3)
    
    #If user types "--help", function print_help() will be called.
    if "--help" in args:
        print_help()
        return

    #These variables are set up so that if statements can just check if the variable is true or false. 
    #The variables check if it's in arguments(args).
    count = None
    last_only = "--last-only" in args
    numbering = "--numbering" in args
    one_line = "--one-line" in args

    #If user types "-c" or "--count", the next argument, which is the number, will be read and stored in the count variable.
    if "-c" in args:
        count = int(args[args.index("-c") + 1])
    elif "--count" in args:
        count = int(args[args.index("--count") + 1])

    #If user doesn't type "-c" or "--count", program will print a message telling them to type it
    if count is None:
        print("Error: Please provide count using -c or --count")
        return

    #This calls the fibonacci function with the user entered "count".
    seq = fibonacci(count)

    #If "last_only" variable is "true", the last number is the list will be printed
    #If it's in the arguments(args), "last_only" variable is "true".
    #Seq[-1] gives the last number in the list.
    if last_only:
        print(seq[-1])
        return

    #If "numbering" variable is "true", a list will be made with the numbers placement and it's fibonacci number.
    #If it's in the arguments(args), "numbering" variable is "true".
    #Enumerate(seq) gives (index, value) pairs.
    if numbering:
        seq = [f"{i+1}:{num}" for i, num in enumerate(seq)]

    #If "one_line" variable is "true", all numbers will be printed on one line operated by commas.
    #If it's in the arguments(args), "one_line" variable is "true".
    #Else, each number is printed on a separate line.
    if one_line:
        print(",".join(map(str, seq)))
    else:
        for num in seq:
            print(num)

#This means that the program will run only if this file is executed.
if __name__ == "__main__":
    main()
